# Generated by Django 5.1.4 on 2025-01-10 04:49

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockupdate',
            name='date',
            field=models.DateField(default=datetime.datetime.today),
        ),
    ]
