# Generated by Django 5.1.4 on 2025-01-10 10:11

import datetime
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0003_alter_stock_symbol_alter_stockupdate_stock'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='stock_id',
        ),
        migrations.AddField(
            model_name='stock',
            name='last_updated',
            field=models.DateField(default=datetime.date.today, help_text='Last updated date'),
        ),
        migrations.AddField(
            model_name='stock',
            name='latest_price',
            field=models.DecimalField(decimal_places=2, default=1, help_text='Latest price of the stock', max_digits=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='stock',
            name='name',
            field=models.CharField(help_text='Name of the stock', max_length=100),
        ),
        migrations.AlterField(
            model_name='stock',
            name='symbol',
            field=models.CharField(help_text='Unique stock symbol', max_length=20, unique=True),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='date',
            field=models.DateField(help_text='Date of the stock update'),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='price',
            field=models.DecimalField(decimal_places=2, help_text='Price of the stock on this date', max_digits=10),
        ),
        migrations.AlterField(
            model_name='stockupdate',
            name='stock',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='updates', to='admin_dashboard.stock'),
        ),
    ]
