# Generated by Django 5.1.4 on 2025-01-10 10:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0004_remove_stock_stock_id_stock_last_updated_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='StockUpdate',
        ),
    ]
