# Generated by Django 5.1.4 on 2025-01-10 10:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0005_delete_stockupdate'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='latest_price',
            new_name='price',
        ),
    ]
