# Generated by Django 5.1.4 on 2025-01-10 11:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_dashboard', '0006_rename_latest_price_stock_price'),
    ]

    operations = [
        migrations.RenameField(
            model_name='stock',
            old_name='price',
            new_name='latest_price',
        ),
    ]
