# Generated by Django 5.1.4 on 2025-01-08 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0002_userregistration_delete_profile'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userregistration',
            name='id',
        ),
        migrations.AddField(
            model_name='userregistration',
            name='user_id',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='aadhar',
            field=models.CharField(max_length=12),
        ),
        migrations.AlterField(
            model_name='userregistration',
            name='pancard',
            field=models.CharField(max_length=10),
        ),
        migrations.AddConstraint(
            model_name='userregistration',
            constraint=models.UniqueConstraint(fields=('aadhar', 'pancard'), name='unique_aadhar_pancard'),
        ),
    ]
