# Generated by Django 5.1.4 on 2025-01-15 18:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0003_remove_userregistration_id_userregistration_user_id_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='userregistration',
            options={'ordering': ['first_name'], 'verbose_name': 'User Registration', 'verbose_name_plural': 'User Registrations'},
        ),
    ]
