# Generated by Django 5.1.4 on 2025-01-15 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0005_alter_userregistration_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userregistration',
            name='funds',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=15),
        ),
    ]
