# Generated by Django 5.1.4 on 2025-01-17 09:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authe', '0007_alter_userregistration_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userregistration',
            name='role',
            field=models.CharField(choices=[('user', 'User'), ('admin', 'Admin')], default='user', max_length=10),
        ),
    ]
